#!/bin/bash

# Script to retrieve Facebook account information from Business ID

# Replace with your access token
ACCESS_TOKEN="YOUR_ACCESS_TOKEN_HERE"
BUSINESS_ID="1856101791959161"
WABA_ID="1659914091647877"

echo "=========================================="
echo "Method 1: Get Business Users/Admins"
echo "=========================================="
echo ""
echo "curl -X GET \\"
echo "  \"https://graph.facebook.com/v21.0/${BUSINESS_ID}/business_users?fields=id,name,email&access_token=${ACCESS_TOKEN}\""
echo ""
echo "This will return:"
echo "{"
echo "  \"data\": ["
echo "    {"
echo "      \"id\": \"...\","
echo "      \"name\": \"Your Name\","
echo "      \"email\": \"your-email@example.com\""
echo "    }"
echo "  ]"
echo "}"
echo ""

echo "=========================================="
echo "Method 2: Get WABA Assigned Users"
echo "=========================================="
echo ""
echo "curl -X GET \\"
echo "  \"https://graph.facebook.com/v21.0/${WABA_ID}/assigned_users?fields=name,email&access_token=${ACCESS_TOKEN}\""
echo ""

echo "=========================================="
echo "Method 3: Get Current Token Owner Info"
echo "=========================================="
echo ""
echo "curl -X GET \\"
echo "  \"https://graph.facebook.com/v21.0/me?fields=id,name,email&access_token=${ACCESS_TOKEN}\""
echo ""

echo "=========================================="
echo "Method 4: Debug Token to See Owner"
echo "=========================================="
echo ""
echo "curl -X GET \\"
echo "  \"https://graph.facebook.com/v21.0/debug_token?input_token=${ACCESS_TOKEN}&access_token=${ACCESS_TOKEN}\""
echo ""
echo "This will show user_id, then query:"
echo "curl -X GET \\"
echo "  \"https://graph.facebook.com/v21.0/{USER_ID}?fields=id,name,email&access_token=${ACCESS_TOKEN}\""
echo ""
